const KEY_COLORS = {
  DEFAULT: "#818384", // BLACK
  LETTER_NOT_PRESENT: "#696969", // GREY
  LETTER_IS_PRESENT: "FFFF00", // YELLOW
  LETTER_IS_HERE: "33CC00", // GREEN
}

export default KEY_COLORS;